---
plugins:
  mdx: true
filters:
  comments: true
rules:
  preset-smarthr: true
  preset-ja-spacing:
    ja-space-between-half-and-full-width: false
  preset-ja-technical-writing:
    sentence-length: false
    ja-no-mixed-period: false
    no-mix-dearu-desumasu: false
    max-kanji-continuous-len: false
  spellcheck-tech-word: true
  prh:
    rulePaths:
      - ./rules.yml
