---
plugins:
  mdx: true
filters:
  comments: true
  allowlist:
    allow:
      - '-github'
rules:
  preset-smarthr:
    ja-no-mixed-period: false
  preset-ja-spacing:
    ja-space-between-half-and-full-width: false
  preset-ja-technical-writing:
    sentence-length: false
    ja-no-mixed-period: false
    max-kanji-continuous-len: false
    no-exclamation-question-mark: false
    max-comma: false
  spellcheck-tech-word: true
  prh:
    rulePaths:
      - ./rules.yml
